version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "20"
    # You can also specify other tool versions:
    # rust: "1.70"
    # golang: "1.20"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for
      # this Jupyter Book so it builds.
      - "jupyter-book config sphinx docs/"
# Build documentation with Mkdocs
mkdocs:
   configuration: mkdocs.yml

# Dependencies required to build your docs
python:
   install:
   - requirements: requirements.txt
